### ISSUE TITLE
Using GPG

### ISSUE THREAD

**Issue by sjiep** [maxisam/mgob#118]
I noticed that GPG was missing in version 2.0.20 and an issue, #107,  that created to point this out. Which resulted in a fix via #109. 

Based on the fix I have two questions. 

1). The fix basically included an extra line to install gnupg directly inside `Dockerfile`. However, the `build.sh` already has a check to install gnupg if the environment flag is set. 

After trying to build the docker image locally, I noticed that it does try to install it, however it fails with the following error:

```log
#14 4.050 ERROR: unable to select packages:
#14 4.052   gnupg-2.4.4-r0:
#14 4.052     breaks: world[gnupg=2.4.3-r1]
```

To me it seems the fix should actually just change the version to 2.4.4-r0, as this seems to be the version is is [available](https://alpine.pkgs.org/3.18/alpine-main-x86_64/gnupg-2.4.4-r0.apk.html) for alpine 3.18. Instead of fixing by including and `apk add` command.

2.) When will there be another releases that has this fix available? It seems I could use the `dev.275` tag for the image, hower these dev versions don't have the variants where the various providers are excluded.

**Comment by maxisam** [comment]
I think you are right, could you make a PR for it and test the dev version, and I will create a release after?
