### ISSUE TITLE
Feature request: Google Cloud Storage authentication using GKE Workload Identity

### ISSUE THREAD

**Issue by panumjp** [maxisam/mgob#123]
It is possible for workloads running in Google Kubernetes Engine to authenticate to Google services without service account key file using workload identity feature:
https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

Authentication using workload identity works automatically if we skip this: https://github.com/maxisam/mgob/blob/main/pkg/backup/gcloud.go#L18-L19

Easiest way to accomplish this is to remove "else" -branch from here: https://github.com/maxisam/mgob/blob/main/pkg/backup/gcloud.go#L24-L26
or by logging something instead of returning error

**Comment by maxisam** [comment]
welcome to make a PR, I will review it and merge after.

**Comment by maxisam** [comment]
this is ship with [2.0.23](https://github.com/maxisam/mgob/releases/tag/2.0.23) Thanks!
