### ISSUE TITLE
Question: What are the usage of `/data` and `/tmp`?

### ISSUE THREAD

**Issue by FlandiaYingman** [maxisam/mgob#128]
Hi, 

In the docker example, it mounts 4 directories

```
docker run -dp 8090:8090 --name mgob \
    -v "/mgob/config:/config" \
    -v "/mgob/storage:/storage" \
    -v "/mgob/tmp:/tmp" \
    -v "/mgob/data:/data" \
    stefanprodan/mgob \
    -LogLevel=info
```

`/config` is configurations and `/storage` is where the backups got saved. They are intuitive.

However, I was confused of the usage of `/data` and `/tmp`. I looked through the documentation and didn't find any description for those two directories. I wonder if I really have to mount them to the host machine.

My guessing:

- I saw there are some mongodb files generated in `/data`, so I think `mgob` creates an internal mongodb, and that is the directory to store the data of that internal mongodb.
- Seems that every log and backups are first created in `/tmp`, then they are moved into `/storage`.

If the guessing are correct, is it the case that we don't need to persist the two directories by mounting them to some directories on the host machine or some docker volumes?

**Comment by sjiep** [comment]
From what I can tell both your guesses are correct. 

`/data` has an internal database file that keeps persists logs and stuff used by the "on-demand" HTTP operations.  
`/tmp` are where the log and backup file orginially are created and if deemed successul are moved to the `/storage` directory. 

Both directory are in fact persisted via anonymous volumes defined by the `VOLUME` instruction inside the `Dockerfile` when not using a host bind-mount, e.g. the `-v "/mgob/tmp:/tmp"` part

**Comment by FlandiaYingman** [comment]
Thanks!
