### ISSUE TITLE
Azure cli no more in image

### ISSUE THREAD

**Issue by arkpoah** [maxisam/mgob#33]
Hello
thx for this fork !

It seems Azure cli is no more in your mgob image, after dump finished I get this error :
```
{"error":"Azure uploading /storage/xxxxx-1666269967.gz to mgob failed /bin/sh: az: not found : exit status 127"}
```

**Comment by maxisam** [comment]
yeah, I disabled those because I don't use them. And I don't have environment to test those. Welcome to test it and make a PR.

**Comment by maxisam** [comment]
I just enabled it. we will see if it works.

**Comment by maxisam** [comment]
could you test this one？If it works, I will cut a release. https://hub.docker.com/layers/maxisam/mgob/dev.100/images/sha256-ee79a085c5018b687d18b5b81de1c328761090d9d3616045d7357f1725098452?context=explore

**Comment by arkpoah** [comment]
thx, I'll test it wednesday

**Comment by arkpoah** [comment]
My uploads (Azure & rclone) work fine with this image :+1:

**Comment by maxisam** [comment]
Thank you for testing

**Comment by maxisam** [comment]
I publish to different image based on the features

https://hub.docker.com/r/maxisam/mgob/tags

for azure you can try this one https://hub.docker.com/layers/maxisam/mgob/1.9.9-azure/images/sha256-5bf9e7c994609f6fe2e78daa980e477c7a0d557041a1a8057c91ccf45a7580b0?context=explore

**Comment by arkpoah** [comment]
I got another missing binary last nights during backups that I missed on my oneshot test yesterday.
I use encyption feature on some databases, and `gpg` command is no more present.

Can you add it in your images plz ?

**Comment by fragolinux** [comment]
> I got another missing binary last nights during backups that I missed on my oneshot test yesterday. I use encyption feature on some databases, and `gpg` command is no more present.
> 
> Can you add it in your images plz ?

still missing: https://github.com/maxisam/mgob/issues/107
