### ISSUE TITLE
Gcloud is not working

### ISSUE THREAD

**Issue by javigualde** [maxisam/mgob#36]
Hello,

We tried to enable Gcloud by using EN_GCLOUD=true, but it's not working.

**Comment by maxisam** [comment]
Somehow it shows GCloud is not installed but it is installed. And it stops http server from starting up.
https://github.com/maxisam/mgob/actions/runs/3353178988/jobs/5556669817#step:11:39

Need to investigate it

**Comment by maxisam** [comment]
will try to install the latest version of gcloud

https://cloud.google.com/sdk/docs/install

**Comment by maxisam** [comment]
Hello @javigualde , please let me know if you are still interested in this feature, or I will just close it. Thanks!

**Comment by maxisam** [comment]
close as no response. Will reopen if there is any more question

**Comment by maxisam** [comment]
it is cool, I got busy lately as well.

**Comment by maxisam** [comment]
btw, the PR is merged.

**Comment by v0ctor** [comment]
Finally, we have tested the whole process with tag `dev.111` and it works fine.

Thank you very much for your help!
