### ISSUE TITLE
feature request: "Purge backups which are older than..."

### ISSUE THREAD

**Issue by medialwerk** [maxisam/mgob#48]
Hello Maxisam,
first: thank you very much for maintaining this repo! (I already used mgob from stefanprodan).
I was searching today for a possibility to purge all backups which are older than 30 days, but sadly I did not found any information about it. Is it already possible? - If not, it would be awesome to support the purge command in the configuration yml.
Thank you very much and best regards,
Ferdinand

**Comment by maxisam** [comment]
I think retention is what you want 

https://github.com/maxisam/mgob/blob/eea0e7771fc8dad48ef6775b2886bfbf5342cf5b/test/travis/mongo-test.yml#L3

**Comment by maxisam** [comment]
close for now. let me know if you still have issues
