### ISSUE TITLE
Upload path changes on 1.10.14

### ISSUE THREAD

**Issue by arkpoah** [maxisam/mgob#50]
Hello,

We use mgob image `1.9.12-all` and tried to upgrade to `1.10.14-all` version and use Azure as storage backend.
with 1.9 version, backup were uploaded in `storage/` path but after upgrade to 1.10, backup are in `tmp/`

Is it a normal behaviour ?

Thanks

**Comment by maxisam** [comment]
this is related to this https://github.com/maxisam/mgob/issues/40

It is intended behavior. If you set a local path, it should move the backup to the path you set.

**Comment by maxisam** [comment]
there are 2 things might relate to this 
1. make sure retention > 0
https://github.com/maxisam/mgob/blob/366207a0954fbfdf684cf0726c8b14e71f94ee08/charts/mgob/values.yaml#L68

2. make usre storagePath for app config is pointing to /storage
