### ISSUE TITLE
how to store passwords securely

### ISSUE THREAD

**Issue by RLutsch** [maxisam/mgob#68]
the helm chart does not support mounting secrets as env making it hard to manage secrets securely:

Let env allow valueFrom option 
Allow more custom detail in the secret option 

This will allow secrets to be pulled cross namespace using replicator then mounted as env without having to put the secret in the configmap. 

happy to do the pr what the process?

**Comment by maxisam** [comment]
just submit the PR. I will review it and merge it thx!

**Comment by maxisam** [comment]
#80 should help

**Comment by dmutterSF** [comment]
Don't know if this is related but I have the plans stored as secrets and don't know how to get mgob to pick them up.
I load the secrets into the container with mountSecrets but mgob only checks the /config directory. I then tried setting the envVar ConfigPath to "/secrets/secretname" but that still gave me the same error message. What am I doing wrong?

Using HelmChart version 1.8.3 and image tag 2.0.18-all

**Comment by maxisam** [comment]
@dmutterSF in Readme

> Load config from environment variables to override config file. syntax: PLAN-ID_KEY_PROPERTY (e.g. mongo-?test_SMTP_SERVER=smtp.company.com)

so you can put your credential in the secret and put your plan in the config now.
