### ISSUE TITLE
Error: unable to install chart

### ISSUE THREAD

**Issue by TLINDEN** [maxisam/mgob#86]
I'm getting this error:
```
Error: looks like "https://maxisam.github.io/mgob/" is not a valid chart repository or cannot be reached: failed to fetch https://maxisam.github.io/mgob/index.yaml : 404 Not Found
```

which can be reproduced manually by:
```
helm repo add maxisam https://maxisam.github.io/mgob/ 
Error: looks like "https://maxisam.github.io/mgob/" is not a valid chart repository or cannot be reached: failed to fetch https://maxisam.github.io/mgob/index.yaml : 404 Not Found
```

The file has been [deleted 5 days ago](https://github.com/maxisam/mgob/commit/ac664c24de8c2c5c1732b67679f3c5de2d4ae863#diff-08c65c1b5ef8384ef0200558777c52f4110afcbbacc880ac5375d555ca97ee3e). Please restore it.

Thanks in advance,
Tom

**Comment by maxisam** [comment]
please try it again, thx for reporting this

**Comment by maxisam** [comment]
feel free to reopen this

**Comment by TLINDEN** [comment]
No it doesn't work.

While the repo uri might work again, now after the latest change the chart version `1.8.2` is not available anymore. But in order to have reproducible builds and deployments I need to stick with that version until the next update round were successfull on test and integration.

So, isn't it possible to host multiple chart versions on github.io somehow?

**Comment by TLINDEN** [comment]
PS: so, `v1.8.3` installs, but you should fix your `index.yaml` generation scheme to include past versions as you did before the change that broke it. If you don't I'd need to maintain a clone of the repo with a fixed `index.yaml` just to make our deployment deployable at any time without any changes. I'd love to avoid that.
